### ISSUE TITLE
How to use RxFit in a background service?

### ISSUE THREAD

**Issue by starkej2** [patloew/RxFit#4]
I am having trouble figuring out how this library is intended to be used in conjunction with a background service. 

I set `handleResolutions` to false on my RxFit instance - I may be missing something, but it seems like to handle the resolutions manually I've ended up copying a bunch of logic from `ResolutionActivity` and `BaseSingle.handleResolutionResult()`. Having to do all of that kind of reduces the usefulness of this library for me.

Basically, I have a switch in my app that starts a JobScheduler service to sync with google fit in the background. When the switch is enabled, I need to request google fit permissions (currently using `RxFit.checkConnection()` to do this as mentioned in #3) then periodically grab history from google fit, notifying the user of resolution issues when they occur.

Would be super helpful if you could provide some direction on how this library is intended to be used without the automatic resolution handling. I wasn't able to find much information about that use case in the sample app or GitHub documentation - just want to make sure I'm not reinventing the wheel by using the library incorrectly. 

Thanks a lot!

**Comment by amouly** [comment]
I have the exact same question. I implemented a lot of logic on my JobScheduler to handle OAuth resolution exceptions.

I'm not sure if I'm doing it the right way, but basically the Service connects to the Activity (which is going to handle the resolution) through the BroadcastManager.

The problem is... I need to validate all this kind of scenarios before the starting the service, because if this starts when the Activity is not there anymore, there is no way to ask the user for permissions.

I'm thinking if there is a way to valide all this first, and then start my Job. I think we are facing the same issue @starkej2.

Thanks!

**Comment by patloew** [comment]
You can use two instances of RxFit, one with `handleResolutions` set to `true`, e.g. for foreground stuff like with Activities, where you can then use `checkConnection()` for letting the lib handle the resolution, and with `false` for background stuff like with Services.
