### ISSUE TITLE
List Subscriptions Exception

### ISSUE THREAD

**Issue by amouly** [patloew/RxFit#5]
Hello. First, thanks for creating this library, it looks really good!

I'm trying to use the Recording API to list the Subscriptions from the user. The code I'm using is the following:

```java
rxFit.recording()
                .listSubscriptions()
                .subscribe(subscription -> {
                    
                }, throwable -> {
                    
                });
```

The problem is when I run this code, I receive the following exception:

`java.lang.NoSuchMethodError: No direct method lambda$subscribe$0(Lcom/google/android/gms/common/api/GoogleApiClient;)V in class Lcom/patloew/rxfit/BaseSingle; or its super classes (declaration of 'com.patloew.rxfit.BaseSingle' appears in "app.apk"`

Could be that I'm calling the incorrect method? Can you clarify how this should works?

Thank you.

**Comment by patloew** [comment]
Do you use an Android Studio 3.0.0 preview? It has problems with retrolambda in the library. Please use Android Studio 2.3.3 for testing with Android O. When Android Studio 3.0.0 stable is released, I'll update the library to remove Retrolambda, since the Android Gradle plugin then can [consume Java 8 libraries](https://developer.android.com/studio/preview/features/java8-support.html).

**Comment by amouly** [comment]
@patloew thank you very much for taking the time to respond.

Yes, I'm using AS 3.0 preview. That makes sense now. I'm going to test on AS stable and let you know.

Thanks!
